session_name: PROD 
shell_command_before:
 - cd ~/ # run as a first command in all panes
 - tmux set status-style bg=purple,fg=colour255
# - tmux set -g message-style fg=white,bold,bg=black
# - tmux set -g window-status-style fg=black,bg=colour11
 - clear
windows:
 - windows_name: default
   layout: even-horizontal
   panes:
   - focus: 'true'
   
